language: objective-c
osx_image: xcode9

branches:
  only:
    - master
    
script:
  - set -o pipefail
  - xcodebuild clean test -project Factoriel.xcodeproj -scheme Factoriel -destination "platform=iOS Simulator,name=iPhone 7,OS=11" ONLY_ACTIVE_ARCH=NO -quiet
